window.LANDING_PAGE_INDUSTRY_CONFIG = {
  EXTRA_DROPDOWN_INDUSTRIES: [
    { id: "restaurants-cafes", name: "Restaurants & Cafés", aliases: ["restaurant", "cafes", "cafe"] },
    { id: "fitness-gyms", name: "Fitness & Gyms", aliases: ["fitness", "gym"] },
    { id: "salons-spas", name: "Salons & Spas", aliases: ["salon", "spas", "spa"] },
    { id: "clinics-healthcare", name: "Clinics & Healthcare", aliases: ["clinics", "healthcare"] },
    { id: "real-estate", name: "Real Estate", aliases: ["real estate", "property"] },
    { id: "pet-care-grooming", name: "Pet Care & Grooming", aliases: ["pet", "grooming"] },
    { id: "wedding-events", name: "Wedding & Events", aliases: ["wedding", "events"] },
    { id: "photography-creative-studios", name: "Photography & Creative Studios", aliases: ["photography", "creative studios"] },
    { id: "dental-orthodontics", name: "Dental & Orthodontics", aliases: ["dental", "orthodontics"] },
    { id: "home-cleaning-services", name: "Home Cleaning Services", aliases: ["home cleaning", "cleaning"] },
    { id: "childcare-daycare", name: "Childcare & Daycare", aliases: ["childcare", "daycare"] },
    { id: "legal-services", name: "Legal Services", aliases: ["legal"] },
    { id: "accounting-bookkeeping", name: "Accounting & Bookkeeping", aliases: ["accounting", "bookkeeping"] },
    { id: "property-management", name: "Property Management", aliases: ["property management"] },
    { id: "coworking-shared-offices", name: "Coworking & Shared Offices", aliases: ["coworking", "shared offices"] },
    { id: "catering-food-delivery", name: "Catering & Food Delivery", aliases: ["catering", "food delivery"] },
    { id: "pharmacy", name: "Pharmacy", aliases: ["pharmacy"] },
    { id: "tattoo-piercing-studios", name: "Tattoo & Piercing Studios", aliases: ["tattoo", "piercing"] },
    { id: "music-arts-education", name: "Music & Arts Education", aliases: ["music", "arts education"] },
    { id: "personal-training", name: "Personal Training", aliases: ["personal training"] },
    { id: "veterinary-clinics", name: "Veterinary Clinics", aliases: ["veterinary", "vet"] },
    { id: "interior-design-architecture", name: "Interior Design & Architecture", aliases: ["interior design", "architecture"] },
    { id: "moving-relocation", name: "Moving & Relocation", aliases: ["moving", "relocation"] },
    { id: "car-rental-fleet", name: "Car Rental & Fleet", aliases: ["car rental", "fleet"] },
    { id: "tourism-tour-operators", name: "Tourism & Tour Operators", aliases: ["tourism", "tour operators"] },
    { id: "language-schools", name: "Language Schools", aliases: ["language schools"] },
    { id: "printing-signage", name: "Printing & Signage", aliases: ["printing", "signage"] },
    { id: "security-services", name: "Security Services", aliases: ["security"] },
    { id: "landscaping-garden-care", name: "Landscaping & Garden Care", aliases: ["landscaping", "garden care"] },
    { id: "swimming-aquatic-centers", name: "Swimming & Aquatic Centers", aliases: ["swimming", "aquatic"] },
    { id: "massage-physiotherapy", name: "Massage & Physiotherapy", aliases: ["massage", "physiotherapy"] },
    { id: "nutrition-dietetics", name: "Nutrition & Dietetics", aliases: ["nutrition", "dietetics"] },
    { id: "driving-schools", name: "Driving Schools", aliases: ["driving schools"] },
    { id: "it-support-msp", name: "IT Support & MSP", aliases: ["it support", "msp"] },
    { id: "staffing-recruitment", name: "Staffing & Recruitment", aliases: ["staffing", "recruitment"] },
    { id: "insurance-brokers", name: "Insurance Brokers", aliases: ["insurance brokers"] },
    { id: "storage-warehousing", name: "Storage & Warehousing", aliases: ["storage", "warehousing"] },
    { id: "film-video-production", name: "Film & Video Production", aliases: ["film", "video production"] },
    { id: "nonprofit-charity", name: "Nonprofit & Charity", aliases: ["nonprofit", "charity"] }
  ],
  INDUSTRY_SCENE_HINTS: {
    "ecommerce-retail": "a retail operations manager checking product dashboard on a tablet inside a modern store stockroom",
    "health-wellness": "a wellness coach reviewing client progress on a tablet in a bright fitness studio",
    "beauty-personal-care": "a beauty studio owner checking appointment notes on a laptop in a salon workspace",
    "travel-hospitality": "a hotel operations staff member working on a booking screen at a reception desk",
    "food-beverage": "a restaurant manager reviewing inventory and orders on a tablet in a busy kitchen",
    "manufacturing": "a factory supervisor checking production metrics on a handheld tablet on the workshop floor",
    "logistics-supply-chain": "a warehouse coordinator operating shipment software on a laptop in a logistics center",
    "professional-services": "a consultant analyzing client data on a laptop at an office desk",
    "clinic-healthcare": "a clinic coordinator reviewing patient schedule on a tablet in a healthcare station",
    "technology-saas": "a product manager monitoring analytics dashboard on dual screens in a tech office",
    "financial-service": "a financial advisor reviewing portfolio charts on a laptop at a professional desk",
    "automotive-repair": "an auto shop manager checking repair workflow on a tablet near service bays",
    "education-training": "an instructor preparing lesson dashboard on a laptop in a training classroom",
    "construction-trades": "a site supervisor reviewing project timeline on a tablet at a construction office",
    "agriculture-farming": "a farm operations manager reviewing crop data on a tablet in an agricultural workspace"
  },
  INDUSTRY_BG_QUERIES: {
    "ecommerce-retail": "person working ecommerce warehouse inventory office environment",
    "health-wellness": "person working wellness fitness studio consultation environment",
    "beauty-personal-care": "person working beauty salon appointment workspace environment",
    "travel-hospitality": "person working hotel reception booking desk environment",
    "food-beverage": "person working restaurant operations kitchen management environment",
    "manufacturing": "person working factory production monitoring environment",
    "logistics-supply-chain": "person working warehouse logistics shipment office environment",
    "professional-services": "person working consulting office client desk environment",
    "clinic-healthcare": "person working clinic healthcare station scheduling environment",
    "technology-saas": "person working software saas office computer environment",
    "financial-service": "person working finance office advisor desk environment",
    "automotive-repair": "person working auto repair service workspace environment",
    "education-training": "person working classroom training education laptop environment",
    "construction-trades": "person working construction planning site office environment",
    "agriculture-farming": "person working agriculture farm operations environment"
  },
  INDUSTRY_BG_IMAGES: {
    "ecommerce-retail": "https://images.unsplash.com/photo-1556740738-b6a63e27c4df?w=1714&q=80",
    "health-wellness": "https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=1714&q=80",
    "beauty-personal-care": "https://images.unsplash.com/photo-1562322140-8baeececf3df?w=1714&q=80",
    "travel-hospitality": "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=1714&q=80",
    "food-beverage": "https://images.unsplash.com/photo-1559339352-11d035aa65de?w=1714&q=80",
    "manufacturing": "https://images.unsplash.com/photo-1581092918484-8313b4ac1f0d?w=1714&q=80",
    "logistics-supply-chain": "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=1714&q=80",
    "professional-services": "https://images.unsplash.com/photo-1552664730-d307ca884978?w=1714&q=80",
    "clinic-healthcare": "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=1714&q=80",
    "technology-saas": "https://images.unsplash.com/photo-1518770660439-4636190af475?w=1714&q=80",
    "financial-service": "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=1714&q=80",
    "automotive-repair": "https://images.unsplash.com/photo-1487754180451-c456f719a1fc?w=1714&q=80",
    "education-training": "https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=1714&q=80",
    "construction-trades": "https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=1714&q=80",
    "agriculture-farming": "https://images.unsplash.com/photo-1500937386664-56d1dfef3854?w=1714&q=80"
  },
  /** Extra dropdown industries → main row in INDUSTRY_BG_IMAGES (shared workplace photo). */
  INDUSTRY_BG_PARENT_MAP: {
    "restaurants-cafes": "food-beverage",
    "fitness-gyms": "health-wellness",
    "salons-spas": "beauty-personal-care",
    "clinics-healthcare": "clinic-healthcare",
    "real-estate": "professional-services",
    "pet-care-grooming": "professional-services",
    "wedding-events": "travel-hospitality",
    "photography-creative-studios": "professional-services",
    "dental-orthodontics": "clinic-healthcare",
    "home-cleaning-services": "professional-services",
    "childcare-daycare": "education-training",
    "legal-services": "professional-services",
    "accounting-bookkeeping": "financial-service",
    "property-management": "professional-services",
    "coworking-shared-offices": "technology-saas",
    "catering-food-delivery": "food-beverage",
    "pharmacy": "clinic-healthcare",
    "tattoo-piercing-studios": "beauty-personal-care",
    "music-arts-education": "education-training",
    "personal-training": "health-wellness",
    "veterinary-clinics": "clinic-healthcare",
    "interior-design-architecture": "construction-trades",
    "moving-relocation": "logistics-supply-chain",
    "car-rental-fleet": "automotive-repair",
    "tourism-tour-operators": "travel-hospitality",
    "language-schools": "education-training",
    "printing-signage": "manufacturing",
    "security-services": "professional-services",
    "landscaping-garden-care": "agriculture-farming",
    "swimming-aquatic-centers": "health-wellness",
    "massage-physiotherapy": "health-wellness",
    "nutrition-dietetics": "health-wellness",
    "driving-schools": "education-training",
    "it-support-msp": "technology-saas",
    "staffing-recruitment": "professional-services",
    "insurance-brokers": "financial-service",
    "storage-warehousing": "logistics-supply-chain",
    "film-video-production": "technology-saas",
    "nonprofit-charity": "professional-services"
  }
};
